-- Add KAdmin file metadata and permissions for the unified file API.
-- This migration is idempotent so it can be used against an existing database.

BEGIN;

CREATE TABLE IF NOT EXISTS public.kadmin_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key character varying(1024) NOT NULL,
    original_name character varying(255) NOT NULL,
    extension character varying(32) NOT NULL DEFAULT '',
    content_type character varying(255) NOT NULL,
    size bigint NOT NULL,
    sha256 character(64) NOT NULL,
    storage character varying(16) NOT NULL,
    bucket character varying(255) NOT NULL DEFAULT '',
    purpose character varying(32) NOT NULL,
    visibility character varying(16) NOT NULL DEFAULT 'private',
    status character varying(16) NOT NULL DEFAULT 'pending',
    created_by bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    expires_at timestamp with time zone,
    CONSTRAINT kadmin_files_object_key_unique UNIQUE (object_key),
    CONSTRAINT kadmin_files_size_check CHECK (size > 0),
    CONSTRAINT kadmin_files_sha256_check CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT kadmin_files_storage_check CHECK (storage IN ('pending', 'local', 'minio')),
    CONSTRAINT kadmin_files_purpose_check CHECK (purpose IN ('avatar', 'editor-image', 'attachment', 'import-temp')),
    CONSTRAINT kadmin_files_visibility_check CHECK (visibility IN ('public', 'private')),
    CONSTRAINT kadmin_files_status_check CHECK (status IN ('pending', 'ready', 'failed', 'deleting', 'deleted')),
    CONSTRAINT kadmin_files_deleted_at_check CHECK (
        (status = 'deleted' AND deleted_at IS NOT NULL)
        OR (status <> 'deleted')
    ),
    CONSTRAINT kadmin_files_expires_at_check CHECK (expires_at IS NULL OR expires_at >= created_at)
);

CREATE INDEX IF NOT EXISTS kadmin_files_created_by_time_index
    ON public.kadmin_files (created_by, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS kadmin_files_purpose_time_index
    ON public.kadmin_files (purpose, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS kadmin_files_cleanup_index
    ON public.kadmin_files (status, updated_at, id)
    WHERE status IN ('pending', 'failed', 'deleting');

CREATE INDEX IF NOT EXISTS kadmin_files_expiration_index
    ON public.kadmin_files (expires_at, id)
    WHERE expires_at IS NOT NULL AND status = 'ready';

INSERT INTO public.goadmin_permissions
    (name, slug, http_method, http_path, created_at, updated_at)
SELECT
    seed.name,
    seed.slug,
    seed.http_method,
    seed.http_path,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM (VALUES
    ('上传文件', 'system:file:upload', 'POST', '/api/files'),
    ('读取文件', 'system:file:read', 'GET', '/api/files*'),
    ('删除文件', 'system:file:delete', 'DELETE', '/api/files/*')
) AS seed(name, slug, http_method, http_path)
WHERE NOT EXISTS (
    SELECT 1
    FROM public.goadmin_permissions permission
    WHERE permission.slug = seed.slug
);

COMMIT;
