-- Add KAdmin scheduled tasks, execution logs, permissions, menu, and built-in jobs.
-- This migration is idempotent so it can be used against an existing database.

BEGIN;

CREATE TABLE IF NOT EXISTS public.kadmin_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL UNIQUE,
    handler character varying(64) NOT NULL,
    cron_expression character varying(255) NOT NULL,
    parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
    description character varying(500) NOT NULL DEFAULT '',
    status character varying(16) NOT NULL DEFAULT 'paused',
    built_in boolean NOT NULL DEFAULT FALSE,
    last_run_at timestamp with time zone,
    next_run_at timestamp with time zone,
    created_by bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT kadmin_jobs_status_check CHECK (status IN ('enabled', 'paused')),
    CONSTRAINT kadmin_jobs_parameters_check CHECK (jsonb_typeof(parameters) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS kadmin_jobs_builtin_handler_unique
    ON public.kadmin_jobs (handler) WHERE built_in = TRUE;
CREATE INDEX IF NOT EXISTS kadmin_jobs_status_next_run_index
    ON public.kadmin_jobs (status, next_run_at, id);

CREATE TABLE IF NOT EXISTS public.kadmin_job_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint REFERENCES public.kadmin_jobs(id) ON DELETE SET NULL,
    job_name character varying(100) NOT NULL,
    handler character varying(64) NOT NULL,
    trigger character varying(16) NOT NULL,
    status character varying(16) NOT NULL,
    output text NOT NULL DEFAULT '',
    error_message text NOT NULL DEFAULT '',
    duration_ms bigint NOT NULL DEFAULT 0,
    triggered_by bigint,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT kadmin_job_logs_trigger_check CHECK (trigger IN ('scheduled', 'manual')),
    CONSTRAINT kadmin_job_logs_status_check CHECK (status IN ('running', 'success', 'failed')),
    CONSTRAINT kadmin_job_logs_duration_check CHECK (duration_ms >= 0),
    CONSTRAINT kadmin_job_logs_finished_check CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE INDEX IF NOT EXISTS kadmin_job_logs_job_time_index
    ON public.kadmin_job_logs (job_id, started_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS kadmin_job_logs_status_time_index
    ON public.kadmin_job_logs (status, started_at DESC, id DESC);

INSERT INTO public.kadmin_jobs
    (name, handler, cron_expression, parameters, description, status, built_in, created_by)
SELECT seed.name, seed.handler, seed.cron_expression, seed.parameters::jsonb,
       seed.description, 'enabled', TRUE, 0
FROM (VALUES
    ('日志清理', 'log_cleanup', '0 2 * * *', '{"retentionDays":30,"taskLogRetentionDays":90}', '清理超过保留期限的请求日志与任务执行日志'),
    ('系统缓存刷新', 'cache_refresh', '0 */6 * * *', '{}', '重新同步 KAdmin 权限与菜单基础数据')
) AS seed(name, handler, cron_expression, parameters, description)
WHERE NOT EXISTS (
    SELECT 1 FROM public.kadmin_jobs job
    WHERE job.built_in = TRUE AND job.handler = seed.handler
)
ON CONFLICT DO NOTHING;

INSERT INTO public.goadmin_permissions
    (name, slug, http_method, http_path, created_at, updated_at)
SELECT seed.name, seed.slug, seed.http_method, seed.http_path, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (VALUES
    ('查看定时任务', 'system:job:list', 'GET', '/api/jobs*'),
    ('创建定时任务', 'system:job:create', 'POST', '/api/jobs'),
    ('修改定时任务', 'system:job:update', 'PUT,PATCH', '/api/jobs/*'),
    ('删除定时任务', 'system:job:delete', 'DELETE', '/api/jobs/*'),
    ('立即执行任务', 'system:job:run', 'POST', '/api/jobs/*/run'),
    ('查看任务日志', 'system:job-log:list', 'GET', '/api/job-logs*')
) AS seed(name, slug, http_method, http_path)
WHERE NOT EXISTS (
    SELECT 1 FROM public.goadmin_permissions permission WHERE permission.slug = seed.slug
);

INSERT INTO public.goadmin_menu
    (parent_id, type, "order", title, icon, uri, plugin_name, created_at, updated_at)
SELECT parent.id, 1, 8, '定时任务', 'lucide:clock-3', '/kadmin/jobs', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM public.goadmin_menu parent
WHERE parent.uri = '/kadmin'
  AND NOT EXISTS (SELECT 1 FROM public.goadmin_menu menu WHERE menu.uri = '/kadmin/jobs')
LIMIT 1;

COMMIT;
