package loginlogs

import (
	"fmt"

	"github.com/GoAdminGroup/go-admin/modules/db"
)

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS public.kadmin_login_audits (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		account character varying(100) NOT NULL DEFAULT '',
		user_id bigint,
		ip character varying(45) NOT NULL DEFAULT '',
		user_agent character varying(1024) NOT NULL DEFAULT '',
		browser character varying(100) NOT NULL DEFAULT '',
		os character varying(100) NOT NULL DEFAULT '',
		status character varying(16) NOT NULL,
		result character varying(32) NOT NULL,
		failure_reason character varying(255) NOT NULL DEFAULT '',
		duration_ms bigint NOT NULL DEFAULT 0,
		occurred_at timestamp with time zone NOT NULL,
		created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT kadmin_login_audits_status_check CHECK (status IN ('success', 'failed')),
		CONSTRAINT kadmin_login_audits_result_check CHECK (result IN ('success', 'account_not_found', 'invalid_password', 'account_disabled', 'account_locked', 'system_error')),
		CONSTRAINT kadmin_login_audits_duration_check CHECK (duration_ms >= 0)
	)`,
	`CREATE INDEX IF NOT EXISTS kadmin_login_audits_account_time_index
		ON public.kadmin_login_audits (account, occurred_at DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS kadmin_login_audits_ip_time_index
		ON public.kadmin_login_audits (ip, occurred_at DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS kadmin_login_audits_status_time_index
		ON public.kadmin_login_audits (status, occurred_at DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS kadmin_login_audits_result_time_index
		ON public.kadmin_login_audits (result, occurred_at DESC, id DESC)`,
	`CREATE TABLE IF NOT EXISTS public.kadmin_login_audit_settings (
		id smallint PRIMARY KEY,
		retention_days integer NOT NULL DEFAULT 90,
		updated_by bigint NOT NULL DEFAULT 0,
		updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT kadmin_login_audit_settings_singleton_check CHECK (id = 1),
		CONSTRAINT kadmin_login_audit_settings_retention_check CHECK (retention_days BETWEEN 1 AND 3650)
	)`,
	`INSERT INTO public.kadmin_login_audit_settings (id, retention_days)
		VALUES (1, 90) ON CONFLICT (id) DO NOTHING`,
}

func EnsureSchema(conn db.Connection) error {
	if conn == nil {
		return fmt.Errorf("login audit database connection is required")
	}
	for _, statement := range schemaStatements {
		if _, err := conn.Exec(statement); err != nil {
			return fmt.Errorf("initialize login audit schema: %w", err)
		}
	}
	return nil
}
