package notifications

import (
	"fmt"

	"github.com/GoAdminGroup/go-admin/modules/db"
)

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS public.kadmin_notifications (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		title character varying(200) NOT NULL,
		content character varying(1000) NOT NULL DEFAULT '',
		link character varying(500) NOT NULL DEFAULT '',
		type character varying(16) NOT NULL DEFAULT 'info',
		is_read boolean NOT NULL DEFAULT FALSE,
		created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT kadmin_notifications_type_check CHECK (type IN ('info', 'success', 'warning'))
	)`,
	`CREATE INDEX IF NOT EXISTS kadmin_notifications_read_time_index
		ON public.kadmin_notifications (is_read, created_at DESC, id DESC)`,
}

// EnsureSchema creates the notification message table if missing.
func EnsureSchema(conn db.Connection) error {
	for _, statement := range schemaStatements {
		if _, err := conn.Exec(statement); err != nil {
			return fmt.Errorf("initialize notifications schema: %w", err)
		}
	}
	return nil
}
