package jobs

import (
	"fmt"

	"github.com/GoAdminGroup/go-admin/modules/db"
)

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS public.kadmin_jobs (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name character varying(100) NOT NULL UNIQUE,
		handler character varying(64) NOT NULL,
		cron_expression character varying(255) NOT NULL,
		parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
		description character varying(500) NOT NULL DEFAULT '',
		status character varying(16) NOT NULL DEFAULT 'paused',
		built_in boolean NOT NULL DEFAULT FALSE,
		last_run_at timestamp with time zone,
		next_run_at timestamp with time zone,
		created_by bigint NOT NULL DEFAULT 0,
		created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT kadmin_jobs_status_check CHECK (status IN ('enabled', 'paused')),
		CONSTRAINT kadmin_jobs_parameters_check CHECK (jsonb_typeof(parameters) = 'object')
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS kadmin_jobs_builtin_handler_unique
		ON public.kadmin_jobs (handler) WHERE built_in = TRUE`,
	`CREATE INDEX IF NOT EXISTS kadmin_jobs_status_next_run_index
		ON public.kadmin_jobs (status, next_run_at, id)`,
	`CREATE TABLE IF NOT EXISTS public.kadmin_job_logs (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		job_id bigint REFERENCES public.kadmin_jobs(id) ON DELETE SET NULL,
		job_name character varying(100) NOT NULL,
		handler character varying(64) NOT NULL,
		trigger character varying(16) NOT NULL,
		status character varying(16) NOT NULL,
		output text NOT NULL DEFAULT '',
		error_message text NOT NULL DEFAULT '',
		duration_ms bigint NOT NULL DEFAULT 0,
		triggered_by bigint,
		started_at timestamp with time zone NOT NULL,
		finished_at timestamp with time zone,
		created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT kadmin_job_logs_trigger_check CHECK (trigger IN ('scheduled', 'manual')),
		CONSTRAINT kadmin_job_logs_status_check CHECK (status IN ('running', 'success', 'failed')),
		CONSTRAINT kadmin_job_logs_duration_check CHECK (duration_ms >= 0),
		CONSTRAINT kadmin_job_logs_finished_check CHECK (finished_at IS NULL OR finished_at >= started_at)
	)`,
	`CREATE INDEX IF NOT EXISTS kadmin_job_logs_job_time_index
		ON public.kadmin_job_logs (job_id, started_at DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS kadmin_job_logs_status_time_index
		ON public.kadmin_job_logs (status, started_at DESC, id DESC)`,
}

type builtInSeed struct {
	Name           string
	Handler        string
	CronExpression string
	Parameters     string
	Description    string
}

var builtInSeeds = []builtInSeed{
	{
		Name:           "日志清理",
		Handler:        HandlerLogCleanup,
		CronExpression: "0 2 * * *",
		Parameters:     `{"retentionDays":30,"taskLogRetentionDays":90}`,
		Description:    "清理超过保留期限的请求日志与任务执行日志",
	},
	{
		Name:           "系统缓存刷新",
		Handler:        HandlerCacheRefresh,
		CronExpression: "0 */6 * * *",
		Parameters:     `{}`,
		Description:    "重新同步 KAdmin 权限与菜单基础数据",
	},
}

func EnsureSchema(conn db.Connection) error {
	for _, statement := range schemaStatements {
		if _, err := conn.Exec(statement); err != nil {
			return fmt.Errorf("initialize task schema: %w", err)
		}
	}
	for _, seed := range builtInSeeds {
		result, err := conn.Exec(`UPDATE public.kadmin_jobs SET name = ?, description = ?, updated_at = CURRENT_TIMESTAMP
			WHERE built_in = TRUE AND handler = ?`, seed.Name, seed.Description, seed.Handler)
		if err != nil {
			return fmt.Errorf("sync built-in task %s: %w", seed.Name, err)
		}
		affected, _ := result.RowsAffected()
		if affected > 0 {
			continue
		}
		if _, err := conn.Exec(`INSERT INTO public.kadmin_jobs
			(name, handler, cron_expression, parameters, description, status, built_in, created_by, created_at, updated_at)
			VALUES (?, ?, ?, ?::jsonb, ?, 'enabled', TRUE, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
			ON CONFLICT DO NOTHING`,
			seed.Name, seed.Handler, seed.CronExpression, seed.Parameters, seed.Description); err != nil {
			return fmt.Errorf("create built-in task %s: %w", seed.Name, err)
		}
	}
	return nil
}
