package codegen

import (
	"fmt"

	"github.com/GoAdminGroup/go-admin/modules/db"
)

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS public.kadmin_codegen_tables (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		table_name character varying(128) NOT NULL UNIQUE,
		module_name character varying(64) NOT NULL,
		class_name character varying(64) NOT NULL,
		business_name character varying(128) NOT NULL,
		route_prefix character varying(64) NOT NULL,
		columns jsonb NOT NULL DEFAULT '[]'::jsonb,
		generated boolean NOT NULL DEFAULT FALSE,
		created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT kadmin_codegen_tables_columns_check CHECK (jsonb_typeof(columns) = 'array')
	)`,
}

// EnsureSchema creates the codegen configuration table if missing.
func EnsureSchema(conn db.Connection) error {
	for _, statement := range schemaStatements {
		if _, err := conn.Exec(statement); err != nil {
			return fmt.Errorf("initialize codegen schema: %w", err)
		}
	}
	return nil
}
