package codegen

import (
	"archive/zip"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Markers identify files owned by the generator. Files without a marker are
// considered hand-written and are never overwritten without confirmation.
const (
	markerGo  = "// Code generated by kadmin codegen. DO NOT EDIT."
	markerVue = "<!-- Code generated by kadmin codegen. DO NOT EDIT. -->"
)

// allowedOutputRoots are the only directories the writer may touch, relative
// to the repository root.
var allowedOutputRoots = []string{
	"internal/kadmin/generated",
	filepath.Join("admin-web", "apps", "web-antd", "src", "views", "kadmin", "generated"),
	filepath.Join("admin-web", "apps", "web-antd", "src", "api", "kadmin", "generated"),
}

// Writer writes generated artifacts into the repository with conflict control.
type Writer struct {
	repoRoot string
}

func NewWriter(repoRoot string) *Writer {
	if repoRoot == "" {
		repoRoot = "."
	}
	return &Writer{repoRoot: repoRoot}
}

func (w *Writer) resolve(artifactPath string) (string, error) {
	if artifactPath == "" {
		return "", fmt.Errorf("artifact path is empty")
	}
	cleaned := filepath.Clean(filepath.FromSlash(artifactPath))
	absolute := filepath.Join(w.repoRoot, cleaned)
	for _, root := range allowedOutputRoots {
		rootAbs := filepath.Join(w.repoRoot, root)
		relative, err := filepath.Rel(rootAbs, absolute)
		if err == nil && relative != "." && !strings.HasPrefix(relative, "..") {
			return absolute, nil
		}
	}
	return "", fmt.Errorf("artifact path %q is outside allowed output roots", artifactPath)
}

type writePlan struct {
	toCreate          []Artifact
	toOverwrite       []Artifact
	conflicts         []string
	conflictArtifacts []Artifact
}

func (w *Writer) plan(artifacts []Artifact) (writePlan, error) {
	plan := writePlan{}
	for _, artifact := range artifacts {
		target, err := w.resolve(artifact.Path)
		if err != nil {
			return writePlan{}, err
		}
		existing, err := os.ReadFile(target)
		if err != nil {
			if os.IsNotExist(err) {
				plan.toCreate = append(plan.toCreate, artifact)
				continue
			}
			return writePlan{}, fmt.Errorf("read %s: %w", target, err)
		}
		if isGeneratedFile(existing) {
			plan.toOverwrite = append(plan.toOverwrite, artifact)
			continue
		}
		plan.conflicts = append(plan.conflicts, artifact.Path)
		plan.conflictArtifacts = append(plan.conflictArtifacts, artifact)
	}
	return plan, nil
}

func isGeneratedFile(content []byte) bool {
	text := string(content)
	return strings.Contains(text, markerGo) || strings.Contains(text, markerVue)
}

func (w *Writer) apply(plan writePlan) error {
	for _, artifact := range append(plan.toCreate, plan.toOverwrite...) {
		target, err := w.resolve(artifact.Path)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return fmt.Errorf("create directory for %s: %w", artifact.Path, err)
		}
		if err := os.WriteFile(target, []byte(artifact.Content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", artifact.Path, err)
		}
	}
	return nil
}

// buildZip packs artifacts into a zip archive.
func buildZip(artifacts []Artifact) ([]byte, error) {
	buffer := &bytes.Buffer{}
	archive := zip.NewWriter(buffer)
	for _, artifact := range artifacts {
		entry, err := archive.Create(artifact.Path)
		if err != nil {
			return nil, fmt.Errorf("zip %s: %w", artifact.Path, err)
		}
		if _, err := entry.Write([]byte(artifact.Content)); err != nil {
			return nil, fmt.Errorf("zip %s: %w", artifact.Path, err)
		}
	}
	if err := archive.Close(); err != nil {
		return nil, fmt.Errorf("close zip: %w", err)
	}
	return buffer.Bytes(), nil
}

func sortedPaths(artifacts []Artifact) []string {
	paths := make([]string, 0, len(artifacts))
	for _, artifact := range artifacts {
		paths = append(paths, artifact.Path)
	}
	sort.Strings(paths)
	return paths
}
