import type { ResourceItem } from './types';

export const demoUser = {
  userId: 'demo',
  username: 'admin',
  realName: '系统管理员',
  roles: ['super'],
  accessCodes: ['system:user:list', 'system:user:add', 'system:user:edit', 'system:user:delete'],
  homePath: '/dashboard',
};

export const initialResources: ResourceItem[] = [
  {
    key: '1001',
    name: '用户管理',
    type: '系统模块',
    owner: '平台组',
    status: 'online',
    priority: 'high',
    progress: 92,
    enabled: true,
    createdAt: '2026-06-20',
    tags: ['RBAC', '菜单'],
  },
  {
    key: '1002',
    name: '角色权限',
    type: '系统模块',
    owner: '平台组',
    status: 'online',
    priority: 'high',
    progress: 86,
    enabled: true,
    createdAt: '2026-06-21',
    tags: ['权限', '按钮'],
  },
  {
    key: '1003',
    name: '文件存储',
    type: '通用服务',
    owner: '基础组',
    status: 'pending',
    priority: 'medium',
    progress: 54,
    enabled: true,
    createdAt: '2026-06-22',
    tags: ['上传', 'MinIO'],
  },
  {
    key: '1004',
    name: '字典管理',
    type: '系统模块',
    owner: '业务组',
    status: 'offline',
    priority: 'high',
    progress: 31,
    enabled: false,
    createdAt: '2026-06-23',
    tags: ['枚举', '缓存'],
  },
  {
    key: '1005',
    name: '代码生成',
    type: '快速开发',
    owner: '工具组',
    status: 'pending',
    priority: 'medium',
    progress: 47,
    enabled: true,
    createdAt: '2026-06-24',
    tags: ['CRUD', '模板'],
  },
  {
    key: '1006',
    name: '操作日志',
    type: '基础设施',
    owner: '审计组',
    status: 'online',
    priority: 'low',
    progress: 73,
    enabled: true,
    createdAt: '2026-06-25',
    tags: ['日志', '审计'],
  },
];
